trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@1
    displayName: 'Clonar o repositório'

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: 'Instalar Node.js'

  - script: npm install -g yarn
    displayName: 'Instalar Yarn'

  - script: yarn
    displayName: 'Instalar dependências'

  - script: yarn playwright install
    displayName: 'Instalar Playwright'

  - script: yarn run e2e
    displayName: 'Executar testes E2E'
