name: 'Execução Manual - $(Date:yyyyMMdd)$(Rev:r)'

trigger:
- main

pool:
  name: Default

steps:
  - checkout: self
    displayName: 'Clonar o repositório'

  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Instalar Node.js'

  - script: npm install -g yarn
    displayName: 'Instalar Yarn'

  - script: yarn
    displayName: 'Instalar dependências'

  - script: yarn run format:check
    displayName: 'Checando Formatação com Prettier'

  - script: yarn playwright install
    displayName: 'Instalar Playwright'

  - script: yarn run e2e
    displayName: 'Executar testes E2E'

  - task: PublishTestResults@2
    displayName: 'Publicar Relatório de Testes'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/results.xml'
    condition: always()