# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    runs-on: self-hosted

    steps:
      # clone do projeto
      - uses: actions/checkout@v4
        with:
          submodules: false

      # instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn
        shell: powershell

      # instalação das dependências
      - name: Instalando dependências
        run: yarn
        shell: powershell

      # Verificação de formatação de código com Prettier
      - name: Checando formatação com Prettier
        run: yarn run format:check
        shell: powershell

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install
        shell: powershell

      # execução dos testes
      - name: Executando testes E2E
        run: yarn run e2e
        shell: powershell

      # Gera o relatório após os testes
      - name: Publicar resultado no PR
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Report
          path: ./test-results/results.xml
          reporter: java-junit

      # Upload do HTML Report do Playwright como artefato
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 30

      - name: Adicionar link do relatório HTML ao resumo
        run: |
          echo "## Relatório HTML do Playwright" >> $GITHUB_STEP_SUMMARY
          echo "Clique [aqui](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/playwright-html-report) para baixar e visualizar o relatório HTML completo." >> $GITHUB_STEP_SUMMARY
        shell: bash # Use 'bash' ou 'pwsh' para scripts que escrevem em GITHUB_STEP_SUMMARY
        if: always()

      - name: Exibir resumo personalizado no Summary
        run: |
          echo "# Meu Relatório Personalizado" >> $GITHUB_STEP_SUMMARY
          echo "**Status dos Testes:** ✅ Aprovados" >> $GITHUB_STEP_SUMMARY
          echo "- Total de Casos de Teste: 100" >> $GITHUB_STEP_SUMMARY
          echo "- Falhas: 0" >> $GITHUB_STEP_SUMMARY
          echo "- Tempo de Execução: 1m 30s" >> $GITHUB_STEP_SUMMARY
        shell: pwsh