# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatilho para execução manual = workflow_dispatch
on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    #maquina que o job vai executar
    runs-on: self-hosted

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # Novo passo para limpar o diretório de relatórios
      - name: Limpando diretório de relatórios antigos
        run: Remove-Item -Path test-results -Recurse -Force

      # instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn
      
      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # execução dos testes
      - name: Executando testes E2E
        run: yarn run e2e

      # Relatórios de Testes - Test ReportAdd commentMore actions
      - name: Publicar relatório de testes
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Report
          path: ./test-results/results.xml
          reporter: java-junit